const ActionTypes = {
  // REST ACTİONS
  REST_SUCCESS: "REST_SUCCESS",
  REST_LOADING: "REST_LOADING",
  REST_ERROR: "REST_ERROR",
  // CART ACTİONS
  CART_SUCCESS: "CART_SUCCESS",
  CART_LOADING: "CART_LOADING",
  CART_ERROR: "CART_ERROR",
  // .
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
};

export default ActionTypes;
